import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',  // ชี้ไปที่ไฟล์ favicon ในโฟลเดอร์ public
  },
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="dracula" lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <div
            class="fixed inset-0 w-64 bg-slate-800 text-white flex flex-col transform transition-transform 
      duration-300 ease-in-out z-50"
          >
            <div class="p-4 text-lg font-bold text-center">My App</div>
            {/* <nav class="flex flex-col space-y-2 mt-4"> */}
            <div
              to="/home"
              class="flex items-center p-2 hover:bg-gray-700 rounded"
            >
              <div class="flex">
                <i class="material-icons items-center flex mr-2">home</i>
                <span class="ml-2">Home</span>
              </div>
            </div>
            <div
              to="/reward"
              class="flex items-center p-2 hover:bg-gray-700 rounded"
            ><div class="flex">
                <i class="material-icons items-center flex mr-2">stars</i>
                <span class="ml-2">Rewards</span>
              </div>
            </div>
            <div
              to="/profile"
              class="flex items-center p-2 hover:bg-gray-700 rounded"
            ><div class="flex">
                <i class="material-icons items-center flex mr-2">person</i>
                <span class="ml-2">Profile</span>
              </div>
            </div>
            <div
              to="/dashboard"
              class="flex items-center p-2 hover:bg-gray-700 rounded"
            ><div class="flex">
                <i class="material-icons items-center flex mr-2">dashboard</i>
                <span class="ml-2">Dashboard</span>
              </div>
            </div>
            <div
              class="flex items-center p-2 hover:bg-gray-700 rounded cursor-pointer"
            >
              <div class="flex">
                <i class="material-icons items-center flex mr-2">logout</i>
                <span class="ml-2">Logout</span>
              </div>
            </div>
          </div>
          {/* <!-- Hamburger Icon for Mobile --> */}
          <button
            class="fixed top-4 left-4 z-50 text-white p-2 rounded-md focus:outline-none sm:hidden"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              class="w-6 h-6"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M4 6h16M4 12h16m-7 6h7"
              />
            </svg>
          </button>
        </div>
        <div class="flex flex-col items-center">
          <header
            class="bg-blue-800 w-full text-white p-4 text-center text-2xl"
          >
            Back Office Points System
          </header>

          <div class="flex flex-col items-center w-full mt-4">
            <div class="bg-white shadow-md rounded-lg p-4 w-full max-w-4xl">
              <h2 class="text-xl font-bold mb-2">
                Hello, !
              </h2>
              <p class="text-gray-600">
                Your points:
                <span class="font-semibold"></span>
              </p>
            </div>
          </div>
        </div>
        {children}

        <footer className="row-start-3 flex gap-6 flex-wrap items-center justify-center">

        </footer>
      </body>
    </html>
  );
}
